runner:
  total_steps: 200000
  gradient_clipping: 1.0e+3
  gradient_accumulate_steps: 2

  log_step: 100
  eval_step: 100
  save_step: 100
  max_keep: 1
  eval_dataloaders:
  - lxt_dev
  - lxt_test
  
optimizer: 
  name: TorchOptim
  torch_optim_name: AdamW
  lr: 1.0e-4

# # comment the whole scheduler config block to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 6000

downstream_expert: 
  save_best_on: lxt_dev

  datarc:
    vad_config:
      min_sec: 32000

    lxt_audio: ./data/superb_second_batch/1.1_resampled/
    lxt_train: ./data/superb_second_batch/1.1_sv_split/train.txt
    lxt_dev: ./data/superb_second_batch/1.1_sv_split/dev.lst
    lxt_test: ./data/superb_second_batch/1.1_sv_split/test.lst

    max_timestep: 128000
    train_batch_size: 20
    eval_batch_size: 1
    num_workers: 8 

  modelrc:
    module:
      XVector  # support to [ XVector, Identity ]
    input_dim: 512
    agg_module: SP # support for ASP / SP / AP / MP 
                   # (Attentive Statistic Pooling / Statistic Pooling / Attentive Pooling / Mean Pooling)
    utter_module:
      UtteranceExtractor # support to [UtteranceExtractor, UtteranceIdentity]
    
    module_config:
      # You can comment it if you do not use this. To demo the usage, we will show all case.
      XVector:
        agg_dim: 1500
        dropout_p: 0.0
        batch_norm: False
      
      Identity:
        no_args: True
        # do nothing    
    
    ObjectiveLoss: AMSoftmaxLoss # You can specify config to AMSoftmaxLoss or SoftmaxLoss
    
    LossConfig:
      # You can comment it if you do not use this. To demo the usage of SoftmaxLoss, we will show all case.
      SoftmaxLoss: 
        no_args: True
    
      # You can comment it if you do not use this. To demo the usage of AMSoftmaxLoss, we will show all case.
      AMSoftmaxLoss:
        s: 30.0
        m: 0.4
